Add status and action strings, and func to retrieve them, including formatting option
bicomsystems/go-libzfs pull request #42
Opened 2022-04-18 09:05 UTC by deitch

As discussed in #41

2022-04-18 09:08 UTC, deitch commented
The only thing I didn't include is where it actually reports which features are unsupported, see [here](https://github.com/openzfs/zfs/blob/533aef2b3c1e65d44526a0776275f21bdcc7cd91/cmd/zpool/zpool_main.c#L2844) and [here](https://github.com/openzfs/zfs/blob/533aef2b3c1e65d44526a0776275f21bdcc7cd91/cmd/zpool/zpool_main.c#L2855). 

To do that, I would need to know what part of `go-libzfs` I would use to find the unsupported features for the equivalent of `zpool_print_unsup_feat`, which is defined [here](https://github.com/openzfs/zfs/blob/3c617c79211659e42039477102646a03a7bfd5e9/include/libzfs.h#L448), imported for `libzfs.h`.

If I can get some pointers, happy to include it, or we can make it a future iteration.

2022-04-18 19:20 UTC, fkasumovic requested changes
zpool_print_unsup_feat is not used,  and if you going to do it, 
do it in the next iteration, and please don't print :-).

Because libzfs C library (wrapped in go here) is not designed as an actual general-purpose API for ZFS but rather as a part of user-space utils of the ZFS, it has these awkward printing functions for the library :-). There is libzfs_core that suppose to be a general-purpose library but does not support all the features and so it's not used here until that changes.

Implement the Pool type method to return a list of unsupported features, and then the developer using go-libzfs can choose to print it or whatever.

func (p *Pool) UnsupportedFeatures() (features map[string]string) {
 ...
}

2022-04-18 19:20 UTC, fkasumovic commented on common.go
> +func GetStatusMessagesFormatted(status PoolStatus) string {
Having these description strings already defined in the lib is handy, and can save a lot of time for the developer, as part of some backend log that will improve troubleshooting experience etc.
But only when you don't have to go beyond that, such as displaying in a different language, displaying a description that would be more intuitive to some end-user, etc. As a developer, I see value in this for such use cases.

But, I'm not sure if the package/library such as go-libzfs should go further than that and have built-in specific formattings for specific kinds of UI such as a terminal, or an opinion on it, on how to display/format these status descriptions.
As you have shown here, when you can reuse these same unmodified descriptions, it's now little effort to make your own GetStatusMessagesFormatted() function with formating that suits requirements.
Different user tools will have different styles, and except terminals have a web or other kind of graphical interface.
I hope you agree with me on this?

2022-04-18 19:20 UTC, fkasumovic commented on common.go
> +func GetStatusMessages(status PoolStatus) (string, string) {
Please change declaration part to

```go 
func GetStatusMessages(status PoolStatus) (msg, action string) {
```
and so remove `var msg, action string` line.

The function will then show up in auto-completion, and documentation with the name and position of returning values.
Otherwise, the developer using this might be confused with the "is status message first or second return value?" question :-(. And will not know for sure without opening the code.

2022-04-19 08:09 UTC, deitch commented on common.go
> +func GetStatusMessagesFormatted(status PoolStatus) string {
Yeah, I was really hesitant about adding this in the first place. I will get rid of it.

2022-04-19 08:10 UTC, deitch commented on common.go
> +func GetStatusMessagesFormatted(status PoolStatus) string {
Done

2022-04-19 08:10 UTC, deitch commented on common.go
> +func GetStatusMessages(status PoolStatus) (string, string) {
Sure, no problem. Everyone has their preferred style, I am good with any reasonable one.

2022-04-19 08:11 UTC, deitch commented on common.go
> +func GetStatusMessages(status PoolStatus) (string, string) {
Done

2022-04-19 08:15 UTC, deitch commented
> zpool_print_unsup_feat is not used, and if you going to do it,
do it in the next iteration, and please don't print :-).

OK, I replace the "it uses the following feature(s) not supported on this system:" part for that message with "it uses feature(s) not supported on this system."

That makes it correct grammatically, while leaving it open in the future to add those details, like you suggested.

Ready for another review.

2022-04-19 08:18 UTC, deitch commented
> Implement the Pool type method to return a list of unsupported features, and then the developer using go-libzfs can choose to print it or whatever.
>
> func (p *Pool) UnsupportedFeatures() (features map[string]string) {
>...
>}

I rather like that idea. But I do not know what goes in that function. The original source for it appears to be in [this thankfully short function](https://github.com/openzfs/zfs/blob/master/lib/libzfs/libzfs_pool.c#L1975-L1991), but unsure what it is doing.

2022-04-19 13:41 UTC, fkasumovic commented
@deitch Well when I take a better look, I think unsupported features is available only for exported pool,

So maybe this should be added in to PoolImportSearch, and returned as a part of ExportedPool type/struct.

``go
ep.Status = PoolStatus(reason)
ep.UnsupportedFeatures = unsupportedFeatures(config)
```

You can wrap with cgo, implementation for fetching the list would probably look like the following:

```go
func unsupportedFeatures(config C.nvlist_ptr) (features map[string]string) {
	features = make(map[string]string)
	var nvinfo, unsup_feat C.nvlist_ptr

	if C.nvlist_exists(config, C.sZPOOL_CONFIG_LOAD_INFO) != 0 {
		nvinfo = C.fnvlist_lookup_nvlist(config, C.sZPOOL_CONFIG_LOAD_INFO)
		if C.nvlist_exists(nvinfo, C.sZPOOL_CONFIG_UNSUP_FEAT) != 0 {
			unsup_feat = C.fnvlist_lookup_nvlist(nvinfo, C.sZPOOL_CONFIG_UNSUP_FEAT)

			for nvp := C.nvlist_next_nvpair(unsup_feat, nil); nvp != nil; {
				desc := C.GoString(C.fnvpair_value_string(nvp))
				name := C.GoString(C.nvpair_name(nvp))
				features[name] = desc

				nvp = C.nvlist_next_nvpair(unsup_feat, nil)
			}
		}
	}
	return
}

```

And then do lot of testing :-)

2022-04-19 13:44 UTC, merged

2022-04-19 14:18 UTC, deitch commented
I hadn't even thought of that, just of recreating the logic. What you did is much smoother. You already pretty much did it.